-- Feature: Advanced Hierarchical Revenue Report (State > City > Seller)
-- Description: Uses CTE for pre-aggregation and ROLLUP for multi-level subtotals.


--Making clean CTE to optimize performance.
--To avoid CROSS JOIN duplication risks.

WITH extract_data AS
(
	SELECT
		seller_id,

--Calculating net revenue per seller

		SUM(((total_bags * 30) - waste_pieces) * rate_per_piece) AS total_amount

	FROM finance.purchases

	GROUP BY
		seller_id
)

SELECT
	s.seller_name,
	l.city,
	l.state,
	SUM(ed.total_amount),

--GROUPING() is used here to differentiate genuine NULL or generated by Subtotal"
--GROUPING() = 0(this column is used while grouping)
--GROUPING() = 1(genertaed by subtotal and this column is ignored while grouping)

	GROUPING(s.seller_name)  AS grouping_seller_name,
	GROUPING(l.city)		AS grouping_city,
	GROUPING(l.state)		AS grouping_state

FROM extract_data ed
INNER JOIN master.sellers s
	ON ed.seller_id = s.seller_id
INNER JOIN master.locations l
	ON s.address_id = l.address_id

--ROLLUP() does hierarchical aggregation, top to down

GROUP BY ROLLUP(l.state,l.city,s.seller_name)

ORDER BY
	l.state        ASC,
	l.city	     ASC,
	s.seller_name	ASC;