-- MODULE 1: GEOGRAPHIC REVENUE & TERRITORY ANALYTICS

-- Feature: Advanced Hierarchical Revenue Report (State > City > Seller)
-- Description: Uses CTE for pre-aggregation and ROLLUP for multi-level subtotals.


--Making clean CTE to optimize performance.
--To avoid CROSS JOIN duplication risks.

WITH extract_data AS
(
	SELECT
		seller_id,

--Calculating net revenue per seller (((total_bags * 30) - waste_pieces) * rate_per_piece)

		SUM(((total_bags * 30) - waste_pieces) * rate_per_piece) AS total_amount

	FROM finance.purchases

	GROUP BY
		seller_id
)

SELECT
	s.seller_name,
	l.city,
	l.state,
	SUM(ed.total_amount) AS total_revenue,

--GROUPING() is used here to differentiate genuine NULL or generated by Subtotal"
--GROUPING() = 0(this column is used while grouping)
--GROUPING() = 1(NULL generated by subtotal and this column is ignored while grouping)

	GROUPING(s.seller_name)  AS grouping_seller_name,
	GROUPING(l.city)		AS grouping_city,
	GROUPING(l.state)		AS grouping_state

FROM extract_data ed
INNER JOIN master.sellers s
	ON ed.seller_id = s.seller_id
INNER JOIN master.locations l
	ON s.address_id = l.address_id

--ROLLUP() does hierarchical aggregation, top to down

GROUP BY ROLLUP(l.state,l.city,s.seller_name)

ORDER BY
	l.state        ASC,
	l.city	     ASC,
	s.seller_name	ASC;


--  MODULE 2: FINANCIAL REPORTS & REVENUE ANALYTICS

-- Feature: 2025 Monthly Revenue Pivot Report (ETL Architecture)
-- Description: Extracts purchase data, transforms it into a monthly pivot table using conditional aggregation, and calculates yearly totals per seller.


--Making clean CTE(extract, transform, load) to optimize performance,maintainability,readability.

--GROUP BY seller_id,TO_CHAR(purchase_date, 'Mon-YY') to capture all transactions accurately.

WITH extract_data AS
(
	SELECT 
		seller_id,
		TO_CHAR(purchase_date, 'Mon-YY') AS purchase_month,
		
--Calculating net revenue (((total_bags * 30) - waste_pieces) * rate_per_piece)

		SUM(((total_bags * 30 )- waste_pieces)*rate_per_piece) AS monthly_purchase
	FROM finance.purchases
	WHERE
		purchase_date >= '2025-01-01' AND purchase_date <= '2025-12-31'
	GROUP BY
		seller_id,
		TO_CHAR(purchase_date, 'Mon-YY')
),

--Using CASE WHEN statement with aggregation SUM to make PIVOT TABLE and GROUP BY seller_id to ensure unique row per seller.

	transform_data AS
(
	SELECT
		seller_id,
		SUM(CASE WHEN purchase_month = 'Jan-25' THEN monthly_purchase ELSE 0 END) AS Jan_25,
		SUM(CASE WHEN purchase_month = 'Feb-25' THEN monthly_purchase ELSE 0 END) AS Feb_25,
		SUM(CASE WHEN purchase_month = 'Mar-25' THEN monthly_purchase ELSE 0 END) AS Mar_25,
		SUM(CASE WHEN purchase_month = 'Apr-25' THEN monthly_purchase ELSE 0 END) AS Apr_25,
		SUM(CASE WHEN purchase_month = 'May-25' THEN monthly_purchase ELSE 0 END) AS May_25,
		SUM(CASE WHEN purchase_month = 'Jun-25' THEN monthly_purchase ELSE 0 END) AS Jun_25,
		SUM(CASE WHEN purchase_month = 'Jul-25' THEN monthly_purchase ELSE 0 END) AS Jul_25,
		SUM(CASE WHEN purchase_month = 'Aug-25' THEN monthly_purchase ELSE 0 END) AS Aug_25,
		SUM(CASE WHEN purchase_month = 'Sep-25' THEN monthly_purchase ELSE 0 END) AS Sep_25,
		SUM(CASE WHEN purchase_month = 'Oct-25' THEN monthly_purchase ELSE 0 END) AS Oct_25,
		SUM(CASE WHEN purchase_month = 'Nov-25' THEN monthly_purchase ELSE 0 END) AS Nov_25,
		SUM(CASE WHEN purchase_month = 'Dec-25' THEN monthly_purchase ELSE 0 END) AS Dec_25
	FROM extract_data 
	GROUP BY
		seller_id
),

--Finding total yearly revenue per seller.

	load_data AS
(
	SELECT
		*,
		(Jan_25+Feb_25+Mar_25+Apr_25+May_25+Jun_25+Jul_25+Aug_25+Sep_25+Oct_25+Nov_25+Dec_25) AS yearly_total
	FROM transform_data

)

--Joining master.sellers to fetch seller_name for business readability.

SELECT 
	s.seller_name,
	ld.*
FROM load_data ld
INNER JOIN master.sellers s
	ON ld.seller_id = s.seller_id


-- MODULE 3: OUTSTANDING BALANCE REPORT

-- Feature : Seller Outstanding Balance Report
-- Description : Aggregates total purchase values and total payments to compute the net outstanding balance for each seller.

-- Making clean CTEs (extract_data_purchase, extract_data_payment) to optimize performance, maintainability, readability.

WITH extract_data_purchase AS
(
     SELECT
          seller_id,

-- Calculating net purchase value (((total_bags * 30) - waste_pieces) * rate_per_piece)

          SUM((((total_bags * 30) - waste_pieces) * rate_per_piece)) AS total_purchase
     FROM finance.purchases

-- GROUP BY seller_id to capture all purchase transactions accurately.

     GROUP BY
          seller_id
),

     extract_data_payment AS
(
     SELECT 
          seller_id,

-- Calculating total payments made by each seller

          SUM(amount_paid) AS total_amount_paid
     FROM finance.payments

-- GROUP BY seller_id to ensure unique row per seller.

     GROUP BY
          seller_id
)

-- Joining master.sellers as base table to fetch seller_name for business readability.
-- Using COALESCE to handle NULL values (mapping to 0) for accurate outstanding_balance calculation.

SELECT
     s.seller_id,
     s.seller_name,
     COALESCE(pur.total_purchase, 0) AS total_purchase,
     COALESCE(pay.total_amount_paid, 0) AS total_amount_paid,
     COALESCE((pur.total_purchase - pay.total_amount_paid), 0) AS outstanding_balance
FROM master.sellers s

-- Using LEFT JOIN on s.seller_id to ensure accurate calculation even if a seller has advance payments but no purchases.

LEFT JOIN extract_data_purchase pur
     ON s.seller_id = pur.seller_id
LEFT JOIN extract_data_payment pay
     ON pay.seller_id = s.seller_id
ORDER BY s.seller_id;


-- MODULE 4: REGIONAL SELLER LEADERBOARD

-- Feature : State-wise Top 2 Sellers Report
-- Description : Aggregates total revenue per seller and uses window functions to rank them within each state, retrieving the top 2 performers.

-- Making clean CTEs (extract_purchase_data, transform_data) to optimize performance, maintainability, readability.

WITH extract_purchase_data AS
(
-- Calculating net revenue: (((total_bags * 30) - waste_pieces) * rate_per_piece)
	SELECT
		seller_id,
		SUM(((total_bags * 30) - waste_pieces) * rate_per_piece) AS total_revenue
	FROM finance.purchases
-- GROUP BY seller_id to capture all purchase transactions accurately.
	GROUP BY seller_id
),
	transform_data AS
(
-- Joining location and seller details, applying DENSE_RANK partitioned by state
	SELECT 
		l.state,
		s.seller_name,
		p.total_revenue,
		DENSE_RANK() OVER w AS state_rank
	FROM master.locations l
	INNER JOIN master.sellers s
		ON l.address_id = s.address_id
	INNER JOIN extract_purchase_data P
		ON p.seller_id = s.seller_id
	WINDOW w AS (
		PARTITION BY l.state
		ORDER BY p.total_revenue DESC
	)
)
-- Fetching the final output filtering only Rank 1 and Rank 2 sellers
SELECT
	*
FROM transform_data
WHERE
	state_rank <= 2;